services:
    _defaults:
        autowire: true
        autoconfigure: true
    nxcore.eventsubscriber.request_data:
        class: OroMediaLab\NxCoreBundle\EventSubscriber\RequestDataSubscriber
        tags: [kernel.event_subscriber]
    nxcore.eventsubscriber.request_validation:
        class: OroMediaLab\NxCoreBundle\EventSubscriber\RequestValidationSubscriber
        tags: [kernel.event_subscriber]
    nxcore.controller.v1.account_controller:
        class: OroMediaLab\NxCoreBundle\Controller\V1\AccountController
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]
    nxcore.controller.v1.user_controller:
        class: OroMediaLab\NxCoreBundle\Controller\V1\UserController
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]
    nxcore.controller.v1.file_upload_controller:
        class: OroMediaLab\NxCoreBundle\Controller\V1\FileUploadController
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]
    nxcore.controller.v1.contact_message_controller:
        class: OroMediaLab\NxCoreBundle\Controller\V1\ContactMessageController
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]
    nxcore.controller.v1.key_value_controller:
        class: OroMediaLab\NxCoreBundle\Controller\V1\KeyValueController
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]
    nxcore.eventlistener.authentication:
        class: OroMediaLab\NxCoreBundle\EventListener\AuthenticationListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onFailure }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onSuccess }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }
    nxcore.command.user_create:
        class: OroMediaLab\NxCoreBundle\Command\UserCreateCommand
        tags:
            - { name: 'console.command', command: 'app:user:create' }
    nxcore.command.user_reset_password:
        class: OroMediaLab\NxCoreBundle\Command\UserResetPasswordCommand
        tags:
            - { name: 'console.command', command: 'app:user:reset-password' }
    nxcore.eventlistener.cors:
        class: OroMediaLab\NxCoreBundle\EventListener\CorsListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    OroMediaLab\NxCoreBundle\Repository\UserRepository:
        tags:
            - { name: doctrine.repository_service }
    OroMediaLab\NxCoreBundle\Repository\KeyValueRepository:
        tags:
            - { name: doctrine.repository_service }