services:
    nxcore.controller.v1.account_controller:
        class: 'OroMediaLab\NxCoreBundle\Controller\V1\AccountController'
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]