services:
    nxcore.controller.account_controller:
        class: 'OroMediaLab\NxCoreBundle\Controller\AccountController'
        tags: ['controller.service_arguments']
        calls:
            - ['setContainer', ['@service_container']]