name: only-staging-to-main

on:
  pull_request:
    branches: [ main ]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR source is staging
        run: |
          echo "Head ref: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "staging" ]; then
            echo "Only PRs from 'staging' can be merged into 'main'."
            exit 1
          fi
          echo "Source branch is staging. OK."
